#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drankregistratie
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="restaurantdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDranken(Dranken instance);
    partial void UpdateDranken(Dranken instance);
    partial void DeleteDranken(Dranken instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Drankregistratie.Properties.Settings.Default.restaurantdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dranken> Drankens
		{
			get
			{
				return this.GetTable<Dranken>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dranken")]
	public partial class Dranken : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAAM;
		
		private string _SOORT;
		
		private string _PRIJS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAAMChanging(string value);
    partial void OnNAAMChanged();
    partial void OnSOORTChanging(string value);
    partial void OnSOORTChanged();
    partial void OnPRIJSChanging(string value);
    partial void OnPRIJSChanged();
    #endregion
		
		public Dranken()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAAM", DbType="VarChar(50)")]
		public string NAAM
		{
			get
			{
				return this._NAAM;
			}
			set
			{
				if ((this._NAAM != value))
				{
					this.OnNAAMChanging(value);
					this.SendPropertyChanging();
					this._NAAM = value;
					this.SendPropertyChanged("NAAM");
					this.OnNAAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOORT", DbType="VarChar(50)")]
		public string SOORT
		{
			get
			{
				return this._SOORT;
			}
			set
			{
				if ((this._SOORT != value))
				{
					this.OnSOORTChanging(value);
					this.SendPropertyChanging();
					this._SOORT = value;
					this.SendPropertyChanged("SOORT");
					this.OnSOORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIJS", DbType="VarChar(50)")]
		public string PRIJS
		{
			get
			{
				return this._PRIJS;
			}
			set
			{
				if ((this._PRIJS != value))
				{
					this.OnPRIJSChanging(value);
					this.SendPropertyChanging();
					this._PRIJS = value;
					this.SendPropertyChanged("PRIJS");
					this.OnPRIJSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
